### ISSUE TITLE
Password Expired

### ISSUE THREAD

**Issue by Epizefiri** [grrnikos/pma#17]
Hi there,
thanks for the script! 

Right after the installation i tried to log in PhpMyAdmin but he replied me with this error

> " Your password has expired. To log in you must change it using a client that supports expired passwords."

I solved log me in the Homestead ssh
`homestead ssh`

Log me in the mysql
`mysql -u root -p` ( the password is "secret")

Changing the password expiration policy

`SET GLOBAL default_password_lifetime = 0;`

log me out from mysql 

`exit`

That's a workaround that reduces security, it will be better if the script fix the problem by himself

**Comment by grrnikos** [comment]
Hello, thanks for your feedback. 

I think this is something that the script shouldn't be responsible for. Maybe I will reconsider in the future if more users struggle with it.

Regards, Nikos.
