### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by yassersharaf** [grrnikos/pma#32]
"Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin"
I renamed config.sample.inc.php to config.inc.php but now I get this error
Wrong permissions on configuration file, should not be world writable!
How to solve this please?

**Comment by kuttumiah** [comment]
> Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin
That is a phpMyAdmin issue. You can check the [bug reporting](https://github.com/phpmyadmin/phpmyadmin/issues/15634) for details.

You config file should have this permission
```
-rw-rw-r--  1 vagrant vagrant   4515 Jun 24 09:59 config.inc.php
```
If that is not what you are seeing try changing it by running the command below in `phpmyadmin` directory

```shell
$ chmod 664 config.inc.php # copy this command without $ sign
```

**Comment by williamdes** [comment]
Let us know if you find solutions or issues that show `Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin`

**Comment by kuttumiah** [comment]
My fork had an older version of this repository.
I merged the changes from of this pull request grrnikos/pma/pull/31 which fixed the issue I was having.
